### set1 - challenge 1
GET http://localhost:3000/set1/challenge1 HTTP/1.1

### set1 - challenge 2
GET http://localhost:3000/set1/challenge2 HTTP/1.1

### set1 - challenge 3
GET http://localhost:3000/set1/challenge3 HTTP/1.1

### set1 - challenge 4
GET http://localhost:3000/set1/challenge4 HTTP/1.1

### set1 - challenge 5
GET http://localhost:3000/set1/challenge5 HTTP/1.1

### set1 - challenge 6
GET http://localhost:3000/set1/challenge6 HTTP/1.1